# Generated by Django 3.2.9 on 2023-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, db_index=True, null=True, unique=True, upload_to='files'),
        ),
    ]
